import { NextRequest, NextResponse } from "next/server";
import { createIssue, findOpenIssueByTitle, parseRepoRef } from "@/lib/rag/github";

type TaskResult = {
  autocompleted_task?: string;
  reasoning?: string;
  subtasks?: string[];
};

function buildIssueBody(result: TaskResult): string {
  const parts: string[] = [];
  if (result.reasoning) parts.push(result.reasoning, "");
  if (result.subtasks?.length) {
    parts.push("## Subtasks", ...result.subtasks.map((s) => `- [ ] ${s}`), "");
  }
  parts.push("---", "_Generated by TaskGenie 🧞 from a vague task._");
  return parts.join("\n");
}

// POST { repoUrl, result } -> opens a GitHub issue from a generated plan.
export async function POST(req: NextRequest) {
  let repoUrl: unknown;
  let result: unknown;
  try {
    ({ repoUrl, result } = await req.json());
  } catch {
    return NextResponse.json({ error: "Invalid JSON body." }, { status: 400 });
  }

  if (typeof repoUrl !== "string" || !repoUrl.trim()) {
    return NextResponse.json(
      { error: "A connected repo is required to create an issue." },
      { status: 400 }
    );
  }
  const r = (result ?? {}) as TaskResult;
  if (!r.autocompleted_task?.trim()) {
    return NextResponse.json(
      { error: "Nothing to file — generate a task first." },
      { status: 400 }
    );
  }

  const token = process.env.GITHUB_TOKEN;
  if (!token || token === "your_key_here") {
    return NextResponse.json(
      {
        error:
          "GITHUB_TOKEN is required to create issues. Add a token with `repo` scope from https://github.com/settings/tokens.",
      },
      { status: 503 }
    );
  }

  try {
    const ref = parseRepoRef(repoUrl.trim());
    const title = r.autocompleted_task.trim().slice(0, 120);

    // Dedupe: if an open issue with the same title already exists, return it
    // instead of filing a duplicate (handles double-clicks / re-runs).
    const existing = await findOpenIssueByTitle(ref, title);
    if (existing) {
      return NextResponse.json({ ...existing, deduped: true });
    }

    const issue = await createIssue(ref, title, buildIssueBody(r));
    return NextResponse.json(issue);
  } catch (err) {
    console.error("[create-issue] failed:", err);
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Could not create issue." },
      { status: 502 }
    );
  }
}
